### PR TITLE
Avoid completing a non-nullable Completer with a nullable value

### PR DESCRIPTION
**Pull request by srawlins**
Implicitly passing a nullable value to a Completer of a non-nullable type can lead to surprising null-asserting exceptions. See https://github.com/dart-lang/sdk/issues/53253 for more details. In this PR, we add an explicit null-assertion, which makes this call in-line with the general concepts of null safety.

Fixes https://github.com/flutter/flutter/issues/137294

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by srawlins** [comment]
Ping for a review; I believe the test failures are unrelated.

**Review by CaseyHillers — APPROVED** [review]

**Comment by srawlins** [comment]
Is there any way to force merge past the existing breakage? I don't have the right authority, maybe?

**Comment by keyonghan** [comment]
> Is there any way to force merge past the existing breakage? I don't have the right authority, maybe?

Unfortunately, cocoon is now allowed with a force merge.

Seems some issue with some package versions: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8761714141529130593/+/u/dashboard/stdout.

**Comment by srawlins** [comment]
I can also disable the cocooon flutter customer tests until cocoon is back in a good state.

**Comment by CaseyHillers** [comment]
@srawlins the issue is fixed at head (based on https://flutter-dashboard.appspot.com/#/build?repo=cocoon&branch=main). Can you rebase your branch?

@keyonghan can we enable the "update branch" GitHub UI for Cocoon?

**Comment by keyonghan** [comment]
That should be helpful. Filed https://github.com/flutter/flutter/issues/140167 to track.

**Comment by srawlins** [comment]
Thanks everyone! Let's merge! 😁

**Comment by keyonghan** [comment]
Same as other repos, we use `autosubmit` label to auto land. Added the label.

**Pull request merged**
