### PR TITLE
CI

### PR DESCRIPTION
**Pull request by dnfield**
pub get, build (if applicable), analysis (using tuneup), and test.

Should we throw dartfmt in?

We should also extend this to do deploys on commits to master, but that can be a follow up.

We should also probably do CI on the mobile/ directory, but that one had a ton of issues that I wasn't sure where to start with for analysis.

### CODE REVIEW

**Comment by dnfield** [comment]
Hm.  I spoke too early.  How do we run the dart2js tests?

**Comment by jonahwilliams** [comment]
you have to run them in a browser `--platform=chrome`, otherwise it spawns the standalone vm

**Comment by dnfield** [comment]
Hm.  They are, unfortunately, not working locally.  Do they work for you and I'm just missing something?

It's also unlikely that the image I'm using has chrome.  I'm going to skip testing these for now.

**Comment by jonahwilliams** [comment]
I test in production

**Comment by jonahwilliams** [comment]
One advantage about moving everything to flutter is that we could unit test most of the app using flutter-tester and skip the browser

**Comment by dnfield** [comment]
Ok, excluding web tests for now.

**Pull request merged**
