### PR TITLE
Revert "Revert "[app_dart] Cache static files for 30 minutes""

### PR DESCRIPTION
**Pull request by godofredoc**
Reverts flutter/cocoon#1121

### CODE REVIEW

**Comment by godofredoc** [comment]
Reverting because https://github.com/flutter/flutter/issues/78917

**Comment by godofredoc** [comment]
Landing as TBR

**Review by CaseyHillers — CHANGES_REQUESTED** [review]
Do not land. This is a reland of a change that doesn't work.

**Comment by godofredoc** [comment]
sounds good!

**Pull request closed without merging**
