### PR TITLE
Makes the get existing pr until function throw more descriptive error

### PR DESCRIPTION
**Pull request by chunhtai**
https://github.com/flutter/flutter/issues/90019

### CODE REVIEW

**Review by keyonghan — APPROVED** [review]
LGTM. This is blocked on https://github.com/flutter/cocoon/pull/1246

**Comment by CaseyHillers** [comment]
Cocoon is now accepting pull requests again. To make your PR compatible,

1. Please update the base to point to main (edit in the GitHub UI)
2. Please rebase on tip of tree. There is now null safety support and you'll have to update your PR to be null safe. There may be some rough edges around the initial migration, so feel free to add fixes as you see fit.

**Comment by chunhtai** [comment]
@keyonghan is there a way to debug the ci.yaml test?

**Comment by keyonghan** [comment]
> @keyonghan is there a way to debug the ci.yaml test?

@CaseyHillers Does your recent change fix the ci.yaml validation hang?

**Comment by CaseyHillers** [comment]
I can't find logs, and I assume this lined up with when we deployed a test version of the dashboard. Can you try pushing an empty commit?

**Pull request merged**
