### PR TITLE
Revert "Revert "Override path_provider""

### PR DESCRIPTION
**Pull request by gw280**
Reverts flutter/cocoon#1089

### CODE REVIEW

**Review by zanderso — APPROVED** [review]
This is still needed as not enough of `dart:ffi` deprecations were reverted to totally avoid the need to roll this dependency forward.

**Comment by zanderso** [comment]
It looks like this is failing on small golden diffs.

**Comment by gw280** [comment]
This is because we want to land https://github.com/flutter/cocoon/pull/1091 which updates the baselines but we can't right now due to the ffi failures fixed by this revert. I've updated this branch to also pull in the rebaselined images so we can atomically land them.

**Comment by gw280** [comment]
Closing as https://github.com/flutter/cocoon/pull/1091 ended up being identical

**Pull request closed without merging**
