### PR TITLE
Disable three lint rules which are being removed.

### PR DESCRIPTION
**Pull request by srawlins**
Each of these three are going to be removed soon.

* avoid_null_checks_in_equality_operators
* package_api_docs
* unsafe_html

Work towards https://github.com/dart-lang/linter/issues/5063 and https://github.com/dart-lang/linter/issues/5001

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md

### CODE REVIEW

**Comment by srawlins** [comment]
A replacement for https://github.com/flutter/cocoon/pull/3991, unless these should be landed one at a time 🤷

**Comment by srawlins** [comment]
@yjbanov who is a good approver for cocoon? 😁

**Comment by srawlins** [comment]
@jtmcdole who is a good approver for cocoon? 😄

**Review by jtmcdole — APPROVED** [review]

**Comment by jtmcdole** [comment]
I didn't realize this had been sitting here for a while. lgtm

**Pull request merged**
