### PR TITLE
Reorder branch replication to replicate from main to master.

### PR DESCRIPTION
**Pull request by godofredoc**
Bug: https://github.com/flutter/flutter/issues/90476

### CODE REVIEW

**Review by keyonghan — APPROVED** [review]
Will this block existing PRs?

**Comment by godofredoc** [comment]
> Will this block existing PRs?
Not sure, probably they'll need some work to move to main but both master and main have the same permissions.

**Comment by CaseyHillers** [comment]
Cocoon is now accepting pull requests again. To make your PR compatible,

1. Please rebase on tip of tree. There is now null safety support and you'll have to update your PR to be null safe. There may be some rough edges around the initial migration, so feel free to add fixes as you see fit.

**Review by CaseyHillers — APPROVED** [review]

**Comment by CaseyHillers** [comment]
FYI: It would be preferred to rebase, as Cocoon ci.yaml changes also require updating the expectations

**Comment by godofredoc** [comment]
> FYI: It would be preferred to rebase, as Cocoon ci.yaml changes also require updating the expectations

This was just the result of moving the base branch to main. There were multiple conflicts with the rebase and many analyzer errors. I'll upload the new version in a few mins.

**Pull request merged**
