### PR TITLE
Enable the comment-only exemption for flutter/flutter

### PR DESCRIPTION
**Pull request by stuartmorgan**
Enables the automatic test exception for changes that can easily be determined to be comment-only, which is currently enabled for flutter/plugins and flutter/packages, for flutter/flutter as well.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by Hixie — APPROVED** [review]
LGTM

**Comment by stuartmorgan** [comment]
@CaseyHillers Any idea what this test failure is? I can repro it locally, but it's unrelated to my change (i.e., it fails if I run it locally on `main` too).

**Comment by CaseyHillers** [comment]
> @CaseyHillers Any idea what this test failure is? I can repro it locally, but it's unrelated to my change (i.e., it fails if I run it locally on main too).

I have a fix in https://github.com/flutter/cocoon/pull/1525. There was a bad PR landed that broke the Cocoon tree

**Comment by CaseyHillers** [comment]
Yes. There's daily releases at 8 AM PST. However, there's an infra code freeze until January 4 - https://github.com/flutter/flutter/issues/95350

**Comment by stuartmorgan** [comment]
Thanks, I misunderstood how the freeze worked; I assumed it was applied to landing PRs here (and that I'd just made it before then). I'll see if it's working in January then :)

**Pull request merged**
