### PR TITLE
Revert "Do not try to submit if PR is not mergeable."

### PR DESCRIPTION
**Pull request by christopherfujino**
Reverts flutter/cocoon#1368

Fixes https://github.com/flutter/flutter/issues/91035

We need the bot to leave the "waiting for tree to go green" label on PRs that are green EXCEPT for the `luci-flutter` check

### CODE REVIEW

**Comment by christopherfujino** [comment]
Further discussion is ongoing in https://github.com/flutter/flutter/issues/91035

**Comment by godofredoc** [comment]
Should we land the logging part first? we may not be able to find the issue if we revert now.

**Review by CaseyHillers — APPROVED** [review]

**Review by godofredoc — APPROVED** [review]
We may also need to revert the logging PR

**Comment by christopherfujino** [comment]
> We may also need to revert the logging PR

I resolved the conflict. We can revert the logging change independently if desired after.

**Pull request merged**
