### PR TITLE
update app_dart/dev/branches.txt for release 1.20.0-7.0.pre

### PR DESCRIPTION
**Pull request by christopherfujino**
Also remove unused code.

### CODE REVIEW

**Comment by keyonghan** [comment]
Would you mind removing these two files completely? They seem to be some legacy files not being called any more.
app_dart/lib/src/request_handlers/utils.dart
app_dart/test/request_handlers/utils_test.dart

**Comment by christopherfujino** [comment]
> Would you mind removing these two files completely? They seem to be some legacy files not being called any more.
> app_dart/lib/src/request_handlers/utils.dart
> app_dart/test/request_handlers/utils_test.dart
> 
> (have been moved to lib/src/foundation/utils.dart)

SGTM

**Comment by christopherfujino** [comment]
> Would you mind removing these two files completely? They seem to be some legacy files not being called any more.
> app_dart/lib/src/request_handlers/utils.dart
> app_dart/test/request_handlers/utils_test.dart
> 
> (have been moved to lib/src/foundation/utils.dart)

Done.

**Comment by christopherfujino** [comment]
Looks like CI is failing on formatting...

**Pull request merged**
