### PR TITLE
Fix null check error when querying Firestore

### PR DESCRIPTION
**Pull request by keyonghan**
Fixes: https://github.com/flutter/flutter/issues/144856

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
Can you add a test for this scenario?

**Comment by keyonghan** [comment]
> Can you add a test for this scenario?

Added for the gold status API code. 

For the Firestore piece of codes, I am not sure how to test it via a unit test as it connects with the gcp server. But I have validated the logic works via a local service.

**Comment by keyonghan** [comment]
Okay. Separated the logic as a function, and added corresponding unit tests to cover.

**Comment by keyonghan** [comment]
A friendly ping:-)

**Review by Piinks — APPROVED** [review]
Flutter_LGTM

**Pull request merged**
