### PR TITLE
Increase the inspected code reviews from 5 to 30.

### PR DESCRIPTION
**Pull request by godofredoc**
This change is also adding logs when the codereview check fails to help
diagnoze auto-submit bot issues.

Bug: https://github.com/flutter/flutter/issues/99033

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by stuartmorgan — COMMENTED** [review]
Shouldn't this have a test that simulates a case like the one we hit failures with?

**Comment by godofredoc** [comment]
> lates a case like the one we hit failures with?

I'm open to ideas on how to create a test that can catch that problem(ran out of ideas). The actual change was in the number of code review items returned by the graphql query.

**Comment by CaseyHillers** [comment]
I don't have any unit test ideas. Ideally, we need E2E tests against a read only GitHub app to prevent this from happening. But there's a lot of security implications we need to work out before we would have a test suite available.

Some of the inspiration for rewriting this code in flutter.dev/go/autosubmit was to remove the graphql code as it's hard to test.

**Review by CaseyHillers — APPROVED** [review]

**Comment by stuartmorgan** [comment]
> The actual change was in the number of code review items returned by the graphql query.

Yes, I hadn't thought that all the way through when I suggested a test.

**Pull request merged**
