### PR TITLE
Remove Dockerfile

### PR DESCRIPTION
**Pull request by CaseyHillers**

### CODE REVIEW

**Review by keyonghan — COMMENTED** [review]
is this file not used anywhere?

**Comment by CaseyHillers** [comment]
> is this file not used anywhere?

IIRC this is from when we used to run Cirrus on presubmit. I figured this is going to be a scream test to see if anything breaks.

**Review by ricardoamador — APPROVED** [review]
LGTM

**Review by keyonghan — APPROVED** [review]

**Comment by CaseyHillers** [comment]
@yusuf-goog (oncall) as FYI 🙏

**Pull request merged**
