### PR TITLE
add fluttergithubbot to list of allow-listed autoroller accounts

### PR DESCRIPTION
**Pull request by christopherfujino**
Related to https://github.com/flutter/flutter/pull/108635
Part of https://github.com/flutter/flutter/issues/106371

@keyonghan is it ok to add this user to this list? I know this account is also used for the flaky bot PRs.

@CaseyHillers this seems like a silly test I've added, since I'm setting `config.rollerAccountsValue` in the test. Should I refactor this code so I can actually test the prod value?

### CODE REVIEW

**Review by keyonghan — CHANGES_REQUESTED** [review]
> @keyonghan is it ok to add this user to this list? I know this account is also used for the flaky bot PRs.

I am afraid not. This will allow all flake/deflake PRs to auto land without test owners' approval. However, we do need test owners' approval for such PRs, as they may not be suitable for different reasons.

I would suggest use a different bot for this rolling purpose, same as other rolling bots.

**Comment by christopherfujino** [comment]
> This will allow all flake/deflake PRs to auto land without test owners' approval. However, we do need test owners' approval for such PRs, as they may not be suitable for different reasons.

Technically it would require an org member adding the `autosubmit` label, and that org member would also have permissions to approve it, even if they're not the code owner.

**Comment by keyonghan** [comment]
> > This will allow all flake/deflake PRs to auto land without test owners' approval. However, we do need test owners' approval for such PRs, as they may not be suitable for different reasons.
> 
> Technically it would require an org member adding the `autosubmit` label, and that org member would also have permissions to approve it, even if they're not the code owner.

Considering flake bot will not auto add `autosubmit` label, this will not cause flake/deflake PRs to auto land. Another question is: the auto submit bot is using `fluttergithubbot` to auto approve roller PRs, I am not sure if the bot could auto approve its own PRs.

**Comment by christopherfujino** [comment]
> > > This will allow all flake/deflake PRs to auto land without test owners' approval. However, we do need test owners' approval for such PRs, as they may not be suitable for different reasons.
> > 
> > 
> > Technically it would require an org member adding the `autosubmit` label, and that org member would also have permissions to approve it, even if they're not the code owner.
> 
> Considering flake bot will not auto add `autosubmit` label, this will not cause flake/deflake PRs to auto land. Another question is: the auto submit bot is using `fluttergithubbot` to auto approve roller PRs, I am not sure if the bot could auto approve its own PRs.

oh, I hadn't considered that

**Comment by christopherfujino** [comment]
Shucks, I'll have to figure out another way to do this then, thanks @keyonghan!

**Pull request closed without merging**
