### PR TITLE
[dashboard] show run and queue time in minutes

### PR DESCRIPTION
**Pull request by XilaiZhang**
Fixes https://github.com/flutter/flutter/issues/83946
This is a starter project regrading to dashboard issue 83946 which shows queue time in minutes instead of seconds.

### CODE REVIEW

**Review by CaseyHillers — COMMENTED** [review]
1. Paste the full link to the issue in the PR description to link it here (https://github.com/flutter/flutter/issues/83946). If this PR fixes it, prepend "Fixes " to the link and GitHub will auto-close the issue
2. Re-apply (1) to the title as well (as a team we usually don't link the issue in the title as the PR will be linked there)
3. Tag the title with just the project (so in this case change [dashboard 83946] -> [dashboard])

Overall, code LGTM! Thanks for the fix

**Review by CaseyHillers — APPROVED** [review]
flutter-lgtm

**Comment by CaseyHillers** [comment]
You'll need to add the label "waiting for tree to go green" to get this submitted

**Review by keyonghan — APPROVED** [review]
LGTM

**Comment by XilaiZhang** [comment]
Thanks a ton for taking the time to review! I am still exploring and I might have some questions to ask

**Pull request merged**
