### PR TITLE
checkboxes for stages were being ignored when set to default again

### PR DESCRIPTION
**Pull request by codebird**
fixes https://github.com/flutter/flutter/issues/103082

### CODE REVIEW

**Comment by codebird** [comment]
@yusuf-goog please check

**Comment by yusuf-goog** [comment]
Yes, that seems to fix it.

**Review by yusuf-goog — APPROVED** [review]

**Comment by codebird** [comment]
@CaseyHillers

**Review by CaseyHillers — APPROVED** [review]
flutter-lgtm

**Pull request merged**
