### PR TITLE
Revert "Support test ownership validation"

### PR DESCRIPTION
**Pull request by zanderso**
Reverts flutter/cocoon#1301

Reverting for https://github.com/flutter/flutter/issues/87321

### CODE REVIEW

**Review by godofredoc — APPROVED** [review]
LGTM

**Comment by CaseyHillers** [comment]
@keyonghan i'll add an integration test for this script today to prevent future breakages

**Comment by keyonghan** [comment]
The failure here doesn't seem related to the cocoon change. I have manually run an led execution based on this PR, it passes: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/8030b72f2ea91065bba62096309f224d1e6777c4bee9458627a5c2ee9111e027/+/build.proto

Looking at  the failure message (https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8840310077976904864/+/u/stderr), it has been happening on earlier tests (like this one: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8840340505364695696/+/u/stderr)
```
WARNING:recipe_engine.internal.commands:recipes.cfg depends on 'recipe_engine' @ c5dc7a267c358f6ba391d200e2fb41d81ce35b23, but 'chromiumos_config' depends on version 60858d08ac9fef6662887e409547f5430ec5d75f.
INFO:recipe_engine.internal.commands.luciexe.cmd:luciexe started, parsing Build message from stdin.
INFO:recipe_engine.internal.commands.luciexe.cmd:finished parsing Build message
INFO:recipe_engine.internal.commands.luciexe.cmd:Synthesized properties: {'$recipe_engine/path': {'cache_dir': '/b/s/w/ir/cache', 'temp_dir': '/b/s/w/ir/x/t'}, 'buildnumber': 18, 'buildername': u'Linux ci_yaml engine roller', '$recipe_engine/runtime': {'is_experimental': False}, '$recipe_engine/buildbucket': {'build': {'status': 'STARTED', 'exe': {'cmd': [u'luciexe'], 'cipdVersion': u'refs/heads/master', 'cipdPackage': u'flutter/recipe_bundles/flutter.googlesource.com/recipes'}, 'createdBy': u'user:flutter-devicelab@flutter-dashboard.iam.gserviceaccount.com', 'tags': [{'value': u'commit/git/6185ae9005ca7dfce3622ce1e4688c729d342b56', 'key': u'buildset'}, {'value': u'commit/gitiles/chromium.googlesource.com/external/github.com/flutter/engine/+/6185ae9005ca7dfce3622ce1e4688c729d342b56', 'key': u'buildset'}, {'value': u'manual', 'key': u'trigger_type'}, {'value': u'zra@google.com', 'key': u'triggered_by'}, {'value': u'luci-scheduler', 'key': u'user_agent'}], 'gracePeriod': '30s', 'builder': {'project': u'flutter', 'builder': u'Linux ci_yaml engine roller', 'bucket': u'prod'}, 'number': 18, 'id': '8840310077976904864', 'startTime': '2021-07-30T04:46:06.461249744Z', 'input': {'experiments': [u'luci.buildbucket.use_bbagent', u'luci.use_realms'], 'properties': {u'goma_jobs': u'200', u'build_android_debug': False, u'recipe': u'infra/ci_yaml', u'build_android_aot': False, u'ios_profile': False, u'clobber': False, u'ios_debug': False, u'build_fuchsia': False, u'gcs_goldens_bucket': u'', u'$recipe_engine/isolated': {u'server': u'https://isolateserver.appspot.com'}, u'build_android_vulkan': False, u'$fuchsia/goma': {u'server': u'rbe-prod1.endpoints.fuchsia-infra-goma-prod.cloud.goog'}, u'$recipe_engine/swarming': {u'server': u'https://chromium-swarm.appspot.com'}, u'build_host': False, u'mastername': u'client.flutter', u'dependencies': [{u'dependency': u'open_jdk', u'version': u'1.8.0u202-b08'}], u'$kitchen': {u'emulate_gce': True}, u'use_cas': True, u'ios_release': False, u'build_windows_uwp': False, u'no_bitcode': False, u'gold_tryjob': False, u'build_ios': False, u'upload_packages': True, u'git_ref': u'6185ae9005ca7dfce3622ce1e4688c729d342b56', u'build_android_jit_release': False, u'os': u'Linux', u'caches': [{u'path': u'builder', u'name': u'builder_linux_engine'}, {u'path': u'java', u'name': u'openjdk'}]}, 'gitilesCommit': {'project': u'external/github.com/flutter/engine', 'host': u'chromium.googlesource.com', 'ref': u'refs/heads/master', 'id': u'6185ae9005ca7dfce3622ce1e4688c729d342b56'}}, 'schedulingTimeout': '21600s', 'infra': {'buildbucket': {'hostname': u'cr-buildbucket.appspot.com', 'requestedProperties': {u'git_ref': u'6185ae9005ca7dfce3622ce1e4688c729d342b56'}}, 'swarming': {'taskServiceAccount': u'flutter-prod-builder@chops-service-accounts.iam.gserviceaccount.com', 'hostname': u'chromium-swarm.appspot.com', 'priority': 29, 'taskId': u'550e8d29bc58e711', 'taskDimensions': [{'value': u'none', 'key': u'device_type', 'expiration': '0s'}, {'value': u'Linux', 'key': u'os', 'expiration': '0s'}, {'value': u'luci.flutter.prod', 'key': u'pool', 'expiration': '0s'}], 'caches': [{'path': u'builder', 'waitForWarmCache': '0s', 'name': u'builder_linux_engine'}, {'path': u'java', 'waitForWarmCache': '0s', 'name': u'openjdk'}, {'path': u'git', 'waitForWarmCache': '0s', 'name': u'git'}, {'path': u'vpython', 'envVar': u'VPYTHON_VIRTUALENV_ROOT', 'waitForWarmCache': '0s', 'name': u'vpython'}, {'path': u'goma', 'waitForWarmCache': '0s', 'name': u'goma_v2'}]}, 'resultdb': {'hostname': u'results.api.cr.dev'}, 'logdog': {'project': u'flutter', 'prefix': u'buildbucket/cr-buildbucket.appspot.com/8840310077976904864', 'hostname': u'logs.chromium.org'}}, 'createTime': '2021-07-30T04:46:06.461249106Z', 'executionTimeout': '1800s'}}, 'bot_id': 'flutter-prod-debian-us-central1-f-9-0x5z'}
INFO:recipe_engine.internal.global_shutdown:Engine quitting normally
```

**Comment by CaseyHillers** [comment]
https://ci.chromium.org/p/flutter/g/cocoon/console

The reason it was reverted is because generate_jspb step started to fail in the ci.yaml roller on that commit.

**Pull request merged**
