### PR TITLE
Remove dart:io dep to build app_flutter for web

### LINKED ISSUE #450: Flutter app fails to build for web because url_launcher does not support web
#447 introduced the dependency on the `url_launcher` plugin which does not current support the web.

https://github.com/flutter/plugins/pull/2119 is a pull request for adding support for this. This issue will probably get resolved on its own :)

### PR DESCRIPTION
**Pull request by CaseyHillers**
Fixes #450 

# Tested

I was able to run a release build on chrome, but ran into a CORS issue. I was able to see an indefinite spinner for the StatusGrid, which is the current behavior.

### CODE REVIEW

**Comment by CaseyHillers** [comment]
Will `dart:io` run on web? I was reading on the Flutter Web documentation not to use dart:io since the web does not have a file system.

**Comment by CaseyHillers** [comment]
See https://flutter.dev/docs/development/platform-integration/web#can-i-use-dartio-with-a-web-app

**Comment by jonahwilliams** [comment]
On the latest flutter master this should work fine in dev and release mode

**Comment by CaseyHillers** [comment]
## Master branch
**Dev**: Works!
**Release**: Works!

## This Web fix branch
**Dev**: Works!
**Release**: Works!

*NOTE:* For release mode I force the Fake CocoonService since the AppEngine service throws CORS network issues since I am running it on localhost.

Thanks @jonahwilliams !

**Pull request closed without merging**
