### PR TITLE
Drain subprocess stdout and stderr before throwing an exception

### PR DESCRIPTION
**Pull request by zanderso**
If a subprocess fails quickly, an exception may be thrown before its output can be echoed to the logger. This PR drains the subprocess output before checking the exit code.

### CODE REVIEW

**Comment by zanderso** [comment]
@keyonghan @godofredoc How does this get deployed? Is landing the change sufficient?

**Comment by godofredoc** [comment]
This needs manually pulling the change and restarting the agents. Please ping keyonghan@ to update and restart the agents, he is the on call this week.

**Comment by keyonghan** [comment]
Will do

**Pull request merged**
