### PR TITLE
Fix import path for bitcask

### PR DESCRIPTION
**Pull request by prologic**
Project has moved to [git.mills.io/prologic/bitcask](https://git.mills.io/prologic/bitcask).

For details on why see: https://github.com/prologic

Thank you! 🙇

### CODE REVIEW

**Comment by christopherfujino** [comment]
@prologic thanks for the PR! As we have this pinned, we do not need to land this now (and we may need a security review to land this). I will close this for now and should we need to upgrade this dependency we will revisit. Again, thanks contributing, and this will save us much confusion later!

**Comment by prologic** [comment]
> @prologic thanks for the PR! As we have this pinned, we do not need to land this now (and we may need a security review to land this). I will close this for now and should we need to upgrade this dependency we will revisit. Again, thanks contributing, and this will save us much confusion later!

I don't think you quite understand.

I migrated **all** of my code off of Github last week.

Your project will not build unless you have bitcask vendored?

Thanks!

**Comment by prologic** [comment]
Looking around your codebase, it doesn't look like you do. Unless you have the dependency proxied with a GOPROXY compatible source you need to get this PR through 🤗

I plan to release v1 this weekend too, so if you want to wait until v1 that's fine too.

**Comment by christopherfujino** [comment]
> > @prologic thanks for the PR! As we have this pinned, we do not need to land this now (and we may need a security review to land this). I will close this for now and should we need to upgrade this dependency we will revisit. Again, thanks contributing, and this will save us much confusion later!
> 
> I don't think you quite understand.
> 
> I migrated **all** of my code off of Github last week.
> 
> Your project will not build unless you have bitcask vendored?
> 
> Thanks!

You are correct, I did not understand. Now I'm wondering why we haven't hit build failures yet...

**Comment by prologic** [comment]
Good question 😁 In any case I recommend you upgrade, many important bug fixes!

Happy to help in any way I can with security reviews!

**Pull request closed without merging**
