### PR TITLE
Build properties theme fixes

### PR DESCRIPTION
**Pull request by flar**
This PR fixes the dark theme and updates the light theme to be more readable based on user feedback in the linked issue.

Fixes flutter/flutter#66929

The property sheet also has a new `Apply` button which keeps the changes when dismissing the dialog and changes the address bar in the browser into a URL that will open the build dashboard with the appropriate filters applied.

Screen shots...

Light theme:
Screen Shot 2020-09-29 at 1 50 25 PM

Dark theme:
Screen Shot 2020-09-29 at 1 48 30 PM

This change will require updates to the golden images.

### CODE REVIEW

**Comment by flar** [comment]
Ugh. Don't look at the diffs yet. I apparently did something odd with my branch.

**Comment by flar** [comment]
OK, I fixed the branch issues. The changes match what I'm submitting.

**Comment by flar** [comment]
Fixes https://github.com/flutter/flutter/issues/66929

**Review by CaseyHillers — APPROVED** [review]
Thanks! LGTM

**Pull request merged**
