### PR TITLE
[scheduler] Publish package to fix gcloud deploys

### PR DESCRIPTION
**Pull request by CaseyHillers**
# Issues

Fixes https://github.com/flutter/flutter/issues/82548

# Tests

```sh
$ cd app_dart
$ dart dev/deploy.dart --project flutter-dashboard --version testchillers
```

https://testchillers-dot-flutter-dashboard.appspot.com/

### CODE REVIEW

**Review by keyonghan — APPROVED** [review]
LGTM

**Review by godofredoc — APPROVED** [review]

**Comment by godofredoc** [comment]
Seems like there are still some problems with the dependencies.

**Comment by CaseyHillers** [comment]
@godofredoc can we force land this to work around https://github.com/flutter/flutter/issues/82705?

This will unblocks deploys in case we need hotfixes

**Comment by godofredoc** [comment]
> s deploys in case we need hotfixes

Sure, done!

**Pull request merged**
