### PR TITLE
[agent] Check in the infra-dialog Xcode project

### PR DESCRIPTION
**Pull request by digiter**
- This project contains a XCUITest that could be applied to dismiss iOS system dialogs.
- Most of this change are boilerplates that I'm not familiar with, please advice on how to reduce them.
- The real content is "infra_dialogUITests.swift" and a few settings that make it compatible with older versions of iOS, e.g. iOS 9.0.
- https://github.com/flutter/cocoon/pull/867 will integrate it as an agent health check.

Bug: https://github.com/flutter/flutter/issues/54792

### CODE REVIEW

**Comment by jmagman** [comment]
You can delete the dummy app since you're not actually loading it in the test.  
@digiter Mind if I push a commit to your fork?  It'll be easier than doing a code review.

**Comment by digiter** [comment]
@jmagman Thanks, that would be great! Or maybe create a PR to cocoon if that's easier.

**Comment by jmagman** [comment]
@digiter I pushed the change to your fork, commit is https://github.com/flutter/cocoon/pull/868/commits/1dbaef5a6bde58ab5741f4f9242379b2fbc70708.

**Comment by digiter** [comment]
Thanks a lot @jmagman !

**Comment by jmagman** [comment]
@digiter I confirmed the test runs and the springboard "app" is loaded, but I wasn't able to actually test closing a real dialog.  Can you check my changes didn't regress that?

**Comment by digiter** [comment]
I tested on a physical iphone, yes, it still can close a real dialog! @jmagman

**Pull request merged**
