### PR TITLE
Add logic to handle a task for a commit that is missing

### PR DESCRIPTION
**Pull request by drewroengoogle**
https://github.com/flutter/flutter/issues/132066
* Adds logic to dart-internal-subscription endpoint, where if there is no commit for the associated task from buildbucket, then create it and add it to the datastore. This is done by adding an optional parameter to the method that creates a Task from a buildbucket build, where you can specify a specific Commit you want use.

Small additional changes:
* Add a commit deep copy method `Commit.from()`
* Move away from the `hash` variable to `sha` since `hash` is reserved

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by keyonghan — COMMENTED** [review]
Do we expect the commit to exist for these dart internal targets? If yes, do we know why we are missing the commit? I would try fixing there instead if possible.

**Comment by drewroengoogle** [comment]
> Do we expect the commit to exist for these dart internal targets? If yes, do we know why we are missing the commit? I would try fixing there instead if possible.

The commit exists referencing main, but not the candidate branch. For example:

Commit hash `abcdef` on `main` has a commit in the datastore `flutter/flutter/main/abcdef`. However, when a new branch is cut from `abcdef` on `flutter-candidate-1`, there is no commit in the datastore for `flutter/flutter/flutter-candidate-1/abcdef`.

I'm not super familiar with github webhooks, is there one for when a new branch is created? We could check for candidate branches and create a new commit there instead of going this route.

**Comment by keyonghan** [comment]
> EDIT: Is this what we're looking for? https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#create

Seems yes. 

When we create a new branch, no corresponding PR will be created but tasks will be triggered. Is this correct? If yes, then a webhook event would solve our problem here. For that event, we just need to call the existing `_addCommit` to create the commit and tasks entries in datastore.

**Comment by drewroengoogle** [comment]
Closing due to https://github.com/flutter/cocoon/pull/3005

**Pull request closed without merging**
