### PR TITLE
Upload CocoaPods 1.16.0 in Ruby cipd package

### PR DESCRIPTION
**Pull request by jmagman**
Update CocoaPods to [1.16.0](https://github.com/CocoaPods/CocoaPods/releases/tag/1.16.0) to pick up Xcode 16 support.

See https://github.com/flutter/cocoon/blob/7683f41ec82e0cc2be65233d625749ed61c0f6c9/cipd_packages/ruby/README.md#installing-cocoapods.

Part of https://github.com/flutter/flutter/issues/157737

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by jmagman** [comment]
I was confused, 1.26 has been tagged but not yet [released](https://github.com/CocoaPods/CocoaPods/releases).  This will have to wait for `gem install cocoapods -v 1.26.0` to succeed.

**Comment by christopherfujino** [comment]
> I was confused, 1.26 has been tagged but not yet [released](https://github.com/CocoaPods/CocoaPods/releases). This will have to wait for `gem install cocoapods -v 1.26.0` to succeed.

acknowledged.

**Comment by jmagman** [comment]
```
Error: Could not rename m4 keg! Check/fix its permissions:
  sudo chown -R swarming /opt/homebrew/Cellar/m4/1.4.19
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8732774199110174961/+/u/build_package/stdout

**Comment by jmagman** [comment]
It passed on rerun, filed https://github.com/flutter/flutter/issues/157803.

**Pull request merged**
