### PR TITLE
[dashboard] Remove obsolete stage filters

### PR DESCRIPTION
**Pull request by KristinBi**
Fixed the issue: https://github.com/flutter/flutter/issues/81062#ref-pullrequest-1121376622
Removing the obsolete stage filter options including ios, android and windows, and keep the luci as the only option.
Also modified the unit test.

### CODE REVIEW

**Comment by CaseyHillers** [comment]
1. In the title, try to add a tag to help make it easier to filter commits (usually the prefix of the first subdir you're working in). In this case it would be [dashboard] Remove obsolete stage filters
2. Run `flutter test` in dashboard to debug why the tests are failing. It looks like you'll need to run `flutter test --update-goldens` (goldens are screenshots of the app)

**Comment by CaseyHillers** [comment]
1. In the title, try to add a tag to help make it easier to filter commits (usually the prefix of the first subdir you're working in). In this case it would be [dashboard] Remove obsolete stage filters
2. Run `flutter test` in dashboard to debug why the tests are failing. It looks like you'll need to run `flutter test --update-goldens` (goldens are screenshots of the app)

**Comment by KristinBi** [comment]
> 

Hi Casey, I only modified the codes for the task_grid_filter_test.dart and I've run flutter test for this file to guarantee  it passed before my first commit. For the second commit, I run flutter test --update-goldens and all tests passed this time. Thanks!

**Review by CaseyHillers — APPROVED** [review]

**Comment by CaseyHillers** [comment]
You can add the waiting for tree to go green label now

**Pull request merged**
