### PR TITLE
Revert "Remove cocoon mirroring from main to master."

### PR DESCRIPTION
**Pull request by CaseyHillers**
Reverts flutter/cocoon#1410

### CODE REVIEW

**Review by godofredoc — APPROVED** [review]

**Comment by godofredoc** [comment]
I believe we can abandon this PR.

**Comment by CaseyHillers** [comment]
> I believe we can abandon this PR.

Were you able to get the sync working in the repo settings?

**Comment by godofredoc** [comment]
nope, created a new master branch in sync with main.

**Comment by CaseyHillers** [comment]
What mechanism would ensure master is staying in sync with main?

**Comment by godofredoc** [comment]
> What mechanism would ensure master is staying in sync with main?

aaah, I thought you were reverting adding the mirroring because it was landed before the master branch was in sync.

**Pull request merged**
