### PR TITLE
Forgot to expose the notification object and BuildV2 pubsub.

### PR DESCRIPTION
**Pull request by ricardoamador**
Forgot to expose the required objects in the newly created protos.

### CODE REVIEW

**Review by keyonghan — APPROVED** [review]
LGTM

**Review by godofredoc — APPROVED** [review]
Should we also update the version somewhere? of pub.dev autoincrements it?

**Comment by ricardoamador** [comment]
Ah yeah let me do that. minor version?

**Review by godofredoc — APPROVED** [review]
Awesome, thank you!

**Pull request merged**
