### PR TITLE
Remove Cirrus output

### PR DESCRIPTION
**Pull request by Piinks**
Follow up to #666 
This removes the log statement for unexpected data from Cirrus. This can throw - again - when there are no Cirrus checks on a PR, like this one: https://github.com/flutter/flutter/pull/51919
When it throws, the whole cron job fails.

### CODE REVIEW

**Comment by Piinks** [comment]
@keyonghan the checks here are failing due to what looks like a cache issue, do you know how I can resolve them?

**Comment by keyonghan** [comment]
> @keyonghan the checks here are failing due to what looks like a cache issue, do you know how I can resolve them?

@CaseyHillers mentioned something deleting some cache folder before. Not sure if related here.

**Comment by CaseyHillers** [comment]
IIRC Keyong is referring to the .pub-cache for when Cocoon deployments.

This looks to be an issue with master on Flutter that LUCI pulled in. I would rerun LUCI in an hour to try and resolve :)

**Comment by keyonghan** [comment]
Hit the same error in my PR: https://github.com/flutter/cocoon/pull/668

**Comment by CaseyHillers** [comment]
Rebase with master, https://github.com/flutter/cocoon/pull/670 should have fixed the issues LUCI is showing.

**Pull request merged**
