### PR TITLE
Make failing tasks in title selectable

### PR DESCRIPTION
**Pull request by jmagman**
Allow users to copy the failing test name to find it in another context (task filter, etc).

### CODE REVIEW

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by jmagman** [comment]
```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown while running async test code:
Golden "goldens/build_dashboard.defaultPropertySheet.dark.png": Pixel test failed, 3.62% diff
detected.
Failure feedback can be found at /b/s/w/ir/k/cocoon/app_flutter/test/failures

When the exception was thrown, this was the stack:
#0      LocalFileComparator.compare (package:flutter_test/src/_goldens_io.dart:108:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
...
````
I'm not sure where these goldens are coming from, these tests pass on my machine.

**Comment by gspencergoog** [comment]
@CaseyHillers do you know what is up with the goldens?

**Comment by jmagman** [comment]
Actually it's not passing for me locally, they are on only running on Linux and I'm on a Mac. So I can reproduce locally. Investigating...

**Comment by CaseyHillers** [comment]
> Actually it's not passing for me locally, they are on only running on Linux and I'm on a Mac. So I can reproduce locally. Investigating...

Cocoon saw issues with goldens on multiple host platforms, so we moved to linux only. These will need to be updated from a linux workstation with `flutter test --update-goldens`. If you don't have a workstation, let me know and I can push the changes for you in this PR.

**Comment by jmagman** [comment]
Going to close for now until the next time I want to copy that text (sorry, future version of myself).

**Pull request closed without merging**
