### PR TITLE
Add logs for autosubmit triage

### PR DESCRIPTION
**Pull request by keyonghan**
For triage: https://github.com/flutter/flutter/issues/107788

### CODE REVIEW

**Comment by ricardoamador** [comment]
Make sure that if any of the objects you are using in the logging are from the github package we import they support the toString method for interpolation. Otherwise looks good. I like that we are adding more logging.

**Review by ricardoamador — APPROVED** [review]
LGTM

**Comment by keyonghan** [comment]
> Make sure that if any of the objects you are using in the logging are from the github package we import they support the toString method for interpolation. Otherwise looks good. I like that we are adding more logging.

Thanks. We used pullRequest here, which has the toString set up.

**Comment by keyonghan** [comment]
> > Make sure that if any of the objects you are using in the logging are from the github package we import they support the toString method for interpolation. Otherwise looks good. I like that we are adding more logging.
> 
> Thanks. We used pullRequest here, which has the toString set up.

Oops, there is only a `toJson` function. I am updating the log here: https://github.com/flutter/cocoon/pull/1988. Sorry for that.

**Pull request merged**
