### PR TITLE
Add ability to set salt grain value for connected mobile device while…

### PR DESCRIPTION
**Pull request by yusufm**
… provisioning host

Added optional parameter to the provisioning script, to allow setting the salt grains value for device_os, which reflects the os of the connected mobile device while provisioning host.

### CODE REVIEW

**Comment by keyonghan** [comment]
what is our plan to update the ios for already provisioned bots?

**Review by godofredoc — APPROVED** [review]

**Comment by yusufm** [comment]
> what is our plan to update the ios for already provisioned bots?

The grain can be set via:

sudo salt flutter-devicelab-mac-19  grains.set 'device_os' 'ios'

**Comment by keyonghan** [comment]
> > what is our plan to update the ios for already provisioned bots?
> 
> The grain can be set via:
> 
> sudo salt flutter-devicelab-mac-19 grains.set 'device_os' 'ios'

Yeah, could we have a bug tracking to add device_os to all existing bots?

**Comment by yusufm** [comment]
> > > what is our plan to update the ios for already provisioned bots?
> > 
> > 
> > The grain can be set via:
> > sudo salt flutter-devicelab-mac-19 grains.set 'device_os' 'ios'
> 
> Yeah, could we have a bug tracking to add device_os to all existing bots?

created #75013

**Review by keyonghan — APPROVED** [review]
LGTM!

**Pull request merged**
