### PR TITLE
Update imports to match the latest directives_ordering analyzer check

### PR DESCRIPTION
**Pull request by jason-simmons**
See https://github.com/dart-lang/linter/issues/2609

### CODE REVIEW

**Review by zanderso — APPROVED** [review]

**Comment by CaseyHillers** [comment]
Overall LGTM.

Can you update the app_flutter/README.md to remove the import style guide?

**Comment by zanderso** [comment]
> Overall LGTM. Can you update the app_flutter/README.md to remove the import style guide?

I replaced the import section with a link to the description of the lint.

**Review by CaseyHillers — APPROVED** [review]
LGTM!

Cocoon is dogfooding submission through only the `waiting for tree to go green`. After an hour of last commit and tests are green the PR will be submitted.

**Comment by zanderso** [comment]
It would be good to land this ASAP since it is needed to unblock a roll.

**Pull request merged**
