### PR TITLE
[app_dart] Fix GitHub check retries

### PR DESCRIPTION
**Pull request by CaseyHillers**
This is a revert done of https://github.com/flutter/cocoon/pull/1407 relating to the 'rerequested' changes. Changes are required in `package:github` to fix, but that tree is currently blocked.

Fixes https://github.com/flutter/flutter/issues/92611

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by CaseyHillers** [comment]
The tests are currently failing on what I believe is an issue in github.dart, and I sent a patch for it in https://github.com/SpinlockLabs/github.dart/pull/276. I locally applied it and the tests pass with that

**Comment by keyonghan** [comment]
> The tests are currently failing on what I believe is an issue in github.dart, and I sent a patch for it in [SpinlockLabs/github.dart#276](https://github.com/SpinlockLabs/github.dart/pull/276). I locally applied it and the tests pass with that

Could you open a bug to track the test failure? This will also make it easy to point to people when they develop cocoon.

**Comment by CaseyHillers** [comment]
> Could you open a bug to track the test failure? This will also make it easy to point to people when they develop cocoon.

Done, I filed https://github.com/SpinlockLabs/github.dart/issues/277. I think this may have surfaced in the week we moved to using models from that packages as some Dart LSCs were made.

**Review by keyonghan — APPROVED** [review]
LGTM.

**Pull request merged**
