### PR TITLE
Fix postsubmit rerun based on checkrun - v2

### PR DESCRIPTION
**Pull request by stuartmorgan**
This is an update of https://github.com/flutter/cocoon/pull/3675, adjusted for v2.

Fixes: https://github.com/flutter/flutter/issues/147007

### CODE REVIEW

**Comment by stuartmorgan** [comment]
I don't have a token that is authorized to push to other people's PRs for flutter/cocoon; rather than set up a new token just for this I opted for making a new PR instead.

This may actually be better though, since it allows for an easy side-by-side of the diffs in the original to see what I changed relative to that one to adapt to v2.

**Comment by stuartmorgan** [comment]
(I don't currently know how to manually test this, but the original was apparently manually tested, and this version passes the unit tests, so I'm moderately confident. I'll make sure this lands separately from anything else so I can test it once it rolls out, and then roll it back right away if needed.)

**Comment by stuartmorgan** [comment]
@christopherfujino Ping?

**Review by christopherfujino — APPROVED** [review]
Oops sorry I forgot about this, LGTM

**Pull request merged**
