### PR TITLE
make pattern more general

### PR DESCRIPTION
**Pull request by christopherfujino**
Fixes https://github.com/flutter/flutter/issues/119197
Fixes https://github.com/flutter/flutter/issues/119151
Fixes https://github.com/flutter/flutter/issues/119147

### CODE REVIEW

**Review by jmagman — APPROVED** [review]
LGTM, thanks!

**Comment by yusuf-goog** [comment]
@christopherfujino looks like there were a few failures that should have been fixed by your change, but still happened? https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20route_test_ios

**Comment by jmagman** [comment]
The fix did work, the symbol doctor is now correctly detecting that it needs to open Xcode:
Screenshot 2023-01-26 at 10 33 32 AM

However just opening Xcode doesn't seem to be enough for the first time case https://github.com/flutter/flutter/issues/118924

**Comment by christopherfujino** [comment]
Yeah, I believe https://github.com/flutter/flutter/issues/118924 is tracking the remaining work to be done (i.e. running `xcrun xcodebuild -runFirstLaunch` to dismiss the new dialog). It's confusing as the two issues surfaced at the same time.

**Comment by jmagman** [comment]
> It's confusing as the two issues surfaced at the same time.

I don't think it's a coincidence, because the ios_debug_symbol_doctor wasn't previously infra failing, it was getting past that point for the tests to run, and they flaked but often eventually sometimes passed.

**Pull request merged**
