### PR TITLE
[app_dart] consider all files under flutter_tools/test to be tests

### PR DESCRIPTION
**Pull request by christopherfujino**
Fixes https://github.com/flutter/flutter/issues/122924

For an example, see the PR https://github.com/flutter/flutter/pull/122856/files, which updated packages/flutter_tools/test/integration.shard/test_utils.dart

### CODE REVIEW

**Comment by christopherfujino** [comment]
@jmagman do you remember if there was a reason we didn't do this before?

**Review by jmagman — APPROVED** [review]
> @jmagman do you remember if there was a reason we didn't do this before?

No, seems like a good idea though. I guess files in this directory are usually caught by the `_test.dart` part.

**Review by jmagman — COMMENTED** [review]
Formatter isn't happy.

**Comment by christopherfujino** [comment]
argh, didn't run dartfmt

**Pull request merged**
